courseapp-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=coursedb
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbp4ss

courseApp:
  image: courseApp
  links:
    - courseapp-mysql:mysql
  ports:
    - 8080:8080